# Bu iþ akýþýnýn adý
name: M3U Playlist Birleştirici

# Ýþ akýþýný tetikleyecek olaylar
on:
  # Her gün gece yarýsý (UTC) otomatik olarak çalýþtýr
  schedule:
    - cron: '0 0 * * *'
  
  # Main branch'e her push yapýldýðýnda çalýþtýr
  push:
    branches:
      - main
      - master
  
  # Manuel olarak çalýþtýrmayý saðlar
  workflow_dispatch:

# Ýþlerin tanýmý
jobs:
  merge-playlists:
    # Ýþin çalýþacaðý iþletim sistemi
    runs-on: ubuntu-latest
    
    # Ýþ akýþýnýn depoya yazma izni olmasý için gerekli ayar
    permissions:
      contents: write

    steps:
      # 1. Adým: Depo kodlarýný çalýþma ortamýna indir
      - name: Depoyu Klonla
        uses: actions/checkout@v4

      # 2. Adým: Python ortamýný kur
      - name: Python'u Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. Adým: Gerekli Python kütüphanesini yükle (requests)
      - name: Bağımlılıkları Yükle
        run: pip install requests

      # 4. Adým: M3U birleþtirme betiğini çalıştır
      - name: M3U Birleştirme Betiğini Çalıştır
        run: python merge_m3u.py

      # 5. Adým: Deðiþiklikleri depoya commit'le ve push'la
      - name: Değişiklikleri Depoya Gönder
        run: |
          # Git için kullanýcý bilgisi ayarla
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Deðiþiklikleri stage'e ekle
          git add karga_aldı.m3u
          
          # Eðer deðiþiklik varsa commit at ve push'la
          # `git diff --staged --quiet` komutu, deðiþiklik yoksa çýkýþ yapar
          if ! git diff --staged --quiet; then
            git commit -m "M3U listesi güncellendi [$(date)]"
            git push
          else
            echo "Herhangi bir değişiklik bulunamadı."
          fi