name: Python scripti her 12 saatte bir çalıştır

on:
  schedule:
    - cron: '0 */12 * * *'  # Her 12 saatte bir
  workflow_dispatch:         # Elle çalıştırma seçeneği

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Repo klonla (push yetkisiyle)
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Gereksinimleri yükle
        run: pip install -r requirements.txt

      - name: Betiği çalıştır
        run: python vodden.py

      - name: m3u dosyasını kontrol et
        run: |
          ls -lh
          cat vodden.m3u || echo "m3u dosyası yok"

      - name: Değişiklikleri GitHub'a geri yükle (force-safe)
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add --force vodden.m3u
          git diff --cached --quiet && echo "Değişiklik yok" || (
            git commit -m "m3u güncellendi [CI]"
            git pull --rebase || echo "pull hatası oldu ama devam ediyoruz"
            git push
          )
